# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-28 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_auto_20180827_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 28, 15, 5, 10, 796061, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mfg_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 28, 15, 5, 10, 796061, tzinfo=utc)),
        ),
    ]
