# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-28 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_auto_20180828_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 28, 15, 46, 47, 175280, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='generic_name',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mfg_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 28, 15, 46, 47, 175280, tzinfo=utc)),
        ),
    ]
