# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-30 04:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import medicines.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0008_auto_20180829_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 30, 4, 4, 20, 774412, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=medicines.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mfg_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 30, 4, 4, 20, 774412, tzinfo=utc)),
        ),
    ]
