# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-31 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0010_auto_20180831_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 31, 18, 35, 32, 18850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mfg_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 31, 18, 35, 32, 18850, tzinfo=utc)),
        ),
    ]
