# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-01 05:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0013_auto_20180901_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 1, 5, 23, 28, 881744, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mfg_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 1, 5, 23, 28, 881744, tzinfo=utc)),
        ),
    ]
